### PR TITLE
alpha1-20240603

### PR DESCRIPTION
**Pull request by poivronvert**
郭明潔
http://52.197.68.128:8000/api/attractions?page=1 
http://52.197.68.128:8000/api/attractions?page=0&keyword=劍潭 
http://52.197.68.128:8000/api/attractions?page=0&keyword=北 
http://52.197.68.128:8000/api/attraction/10
http://52.197.68.128:8000/api/mrts

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
- nextPage field of the last page should be null. For example, the nextPage field of http://52.197.68.128:8000/api/attractions?page=4 and http://52.197.68.128:8000/api/attractions?page=1&keyword=%E5%8C%97 should be null.
- response format of http://52.197.68.128:8000/api/mrts is incorrect.

**Comment by poivronvert** [comment]
- nextPage: `next page` shows null for those last pages.
- mrt format modified according to the API.

**Review by cwpeng — CHANGES_REQUESTED** [review]
nextPage of http://52.197.68.128:8000/api/attractions?page=3 and http://52.197.68.128:8000/api/attractions?page=0&keyword=%E5%8C%97 should not be null.

**Comment by poivronvert** [comment]
fix last page

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
